<?php

return [
    'agent_presence_ttl_seconds' => 45,
    'polling_interval_seconds' => 7,
    'max_messages_per_minute' => 35,
    'contexts' => [
        'landing' => [
            'assistant_name' => 'Asistente GymSystem',
            'assistant_subtitle' => 'Soporte comercial para gimnasios',
            'welcome_message' => 'Hola, soy tu asistente. Te ayudo con dudas de planes, demo, implementación y operación de GymSystem.',
            'fallback_message' => 'Te puedo orientar por módulo: recepción, clientes, planes, caja, ventas/inventario, reportes, sucursales y portal cliente.',
            'quick_replies' => [
                [
                    'key' => 'demo_scope',
                    'label' => '¿Qué incluye la demo?',
                    'response' => 'La demo muestra flujo real: panel, recepción, clientes, membresías, caja, ventas/inventario y reportes, en un entorno temporal.',
                    'escalate' => false,
                ],
                [
                    'key' => 'plans_pricing',
                    'label' => 'Planes y precios',
                    'response' => 'Manejamos planes por nivel operativo del gimnasio. Si me compartes número de sedes y módulos que usarás, te recomiendo el plan correcto.',
                    'escalate' => false,
                ],
                [
                    'key' => 'implementation_migration',
                    'label' => 'Implementación o migración',
                    'response' => 'Te guiamos en la carga inicial: clientes, planes, usuarios y configuración de caja/recepción. También podemos acompañar migración desde Excel.',
                    'escalate' => false,
                ],
                [
                    'key' => 'reception_checkin',
                    'label' => 'Recepción y acceso',
                    'response' => 'Sí, GymSystem incluye recepción con control de accesos y seguimiento de asistencias para operación diaria del gimnasio.',
                    'escalate' => false,
                ],
                [
                    'key' => 'sales_inventory_scope',
                    'label' => 'Ventas e inventario',
                    'response' => 'Incluye ventas de productos, control de stock, entradas/salidas y reportes del módulo comercial para tu gimnasio.',
                    'escalate' => false,
                ],
                [
                    'key' => 'multi_branch_scope',
                    'label' => '¿Maneja sucursales?',
                    'response' => 'Sí, puedes administrar varias sedes y trabajar en contexto por sucursal o vista global según plan habilitado.',
                    'escalate' => false,
                ],
                [
                    'key' => 'client_portal_scope',
                    'label' => 'Portal cliente y app',
                    'response' => 'También puedes habilitar portal cliente y experiencia móvil (PWA) para consultas, progreso y acciones del usuario final.',
                    'escalate' => false,
                ],
                [
                    'key' => 'billing_question',
                    'label' => 'Facturación y suscripción',
                    'response' => 'Puedo ayudarte con pagos, renovación, reactivación y facturación del servicio. Si quieres, te paso con un representante.',
                    'escalate' => false,
                ],
                [
                    'key' => 'contact_representative',
                    'label' => 'Contactar representante',
                    'response' => 'Listo, ya estoy notificando a soporte SuperAdmin para que te atienda por este chat.',
                    'escalate' => true,
                ],
            ],
        ],
        'gym_panel' => [
            'assistant_name' => 'Soporte operativo',
            'assistant_subtitle' => 'Asistencia para gimnasios activos',
            'welcome_message' => 'Hola equipo. Este canal es para soporte operativo del gimnasio con SuperAdmin.',
            'fallback_message' => 'Puedo ayudarte por módulo: recepción, clientes/membresías, caja, ventas/inventario, reportes, sucursales, usuarios y portal cliente.',
            'quick_replies' => [
                [
                    'key' => 'reception_issue',
                    'label' => 'Problema en recepción',
                    'response' => 'Para revisar recepción, comparte: sede, acción exacta (check-in/check-out) y el mensaje mostrado. Con eso te damos pasos precisos.',
                    'escalate' => false,
                ],
                [
                    'key' => 'clients_memberships_issue',
                    'label' => 'Clientes o membresías',
                    'response' => 'Si es en clientes/membresías, indícame el cliente y qué acción falla (crear, editar, renovar, ajustar). Te guío paso a paso.',
                    'escalate' => false,
                ],
                [
                    'key' => 'cash_issue',
                    'label' => 'Caja (apertura/cierre)',
                    'response' => 'En caja revisamos apertura, movimientos y cierre. Dime la fecha, el turno y el paso donde se detiene para resolverlo rápido.',
                    'escalate' => false,
                ],
                [
                    'key' => 'sales_inventory_issue',
                    'label' => 'Ventas e inventario',
                    'response' => 'Para ventas/inventario, dime producto, movimiento y pantalla exacta. También indica si la caja estaba abierta al registrar la venta.',
                    'escalate' => false,
                ],
                [
                    'key' => 'reports_issue',
                    'label' => 'Reportes o exportación',
                    'response' => 'Para reportes, indícame el rango de fechas, el reporte y si falla vista, CSV o PDF. Con eso validamos filtros y permisos.',
                    'escalate' => false,
                ],
                [
                    'key' => 'users_permissions',
                    'label' => 'Usuarios y permisos',
                    'response' => 'Te ayudo con perfiles owner/cajero y permisos por módulo. Dime qué usuario debe ver o no ver cada sección.',
                    'escalate' => false,
                ],
                [
                    'key' => 'branches_scope_issue',
                    'label' => 'Sucursales y contexto',
                    'response' => 'Si es tema de sucursales, revisamos contexto (sede/global), permisos y plan habilitado para multi-sucursal.',
                    'escalate' => false,
                ],
                [
                    'key' => 'portal_pwa_issue',
                    'label' => 'Portal cliente y PWA',
                    'response' => 'Para portal cliente o app PWA, dime qué pantalla falla y el dispositivo/navegador para darte una solución exacta.',
                    'escalate' => false,
                ],
                [
                    'key' => 'subscription_billing',
                    'label' => 'Ayuda con suscripción',
                    'response' => 'Claro. Puedo registrar pagos, renovación o reactivación para que SuperAdmin lo priorice.',
                    'escalate' => false,
                ],
                [
                    'key' => 'training_help',
                    'label' => 'Capacitación del equipo',
                    'response' => 'Podemos coordinar capacitación enfocada en recepción, clientes, caja y reportes según tu operación.',
                    'escalate' => false,
                ],
                [
                    'key' => 'contact_representative',
                    'label' => 'Contactar representante',
                    'response' => 'Listo, estoy pasando tu conversación a soporte SuperAdmin.',
                    'escalate' => true,
                ],
            ],
        ],
    ],
    'keyword_triggers' => [
        'representative' => ['representante', 'agente', 'humano', 'asesor', 'escalar', 'llamada', 'whatsapp'],
        'technical' => ['error', 'falla', 'bug', 'no funciona', 'problema técnico', 'problema tecnico', 'caído', 'caido'],
        'billing' => ['factura', 'facturación', 'facturacion', 'pago', 'cobro', 'suscripción', 'suscripcion', 'renovación', 'renovacion', 'reactivación', 'reactivacion'],
        'training' => ['capacitación', 'capacitacion', 'entrenamiento', 'equipo', 'inducción', 'induccion'],
        'plans' => ['plan', 'precio', 'precios', 'cotización', 'cotizacion'],
        'demo' => ['demo', 'prueba', 'probar'],
        'implementation' => ['implementación', 'implementacion', 'configuración', 'configuracion', 'arranque'],
        'migration' => ['migración', 'migracion', 'importar', 'excel', 'traspaso'],
        'reception' => ['recepción', 'recepcion', 'check-in', 'check in', 'asistencia', 'ingreso', 'acceso', 'rfid', 'qr'],
        'clients' => ['cliente', 'clientes', 'ficha', 'registro cliente', 'datos cliente'],
        'memberships' => ['membresía', 'membresia', 'membresías', 'membresias', 'vencimiento', 'renovar plan'],
        'cash' => ['caja', 'apertura', 'cerrar caja', 'cierre', 'movimiento', 'efectivo', 'arqueo'],
        'sales_inventory' => ['ventas', 'venta', 'inventario', 'producto', 'stock', 'entrada de stock', 'salida de stock'],
        'reports' => ['reporte', 'reportes', 'ingresos', 'asistencia', 'exportar', 'csv', 'pdf'],
        'staff' => ['cajero', 'cajeros', 'usuario', 'usuarios', 'permiso', 'permisos', 'rol'],
        'branches' => ['sucursal', 'sucursales', 'global', 'sede', 'sedes', 'multisucursal'],
        'portal_pwa' => ['portal cliente', 'app', 'pwa', 'notificación', 'notificacion', 'push', 'instalar app'],
        'schedule' => ['horario', 'atención', 'atencion', 'disponible', 'disponibilidad'],
    ],
    'agent_online_message' => 'SuperAdmin está conectado. Ya puedes continuar la conversación en vivo por este chat.',
    'agent_offline_message' => 'SuperAdmin no está conectado por ahora. El bot seguirá ayudándote y dejaremos tu caso en cola para respuesta humana.',
];
